# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: E2E Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  chrome:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: 3.12

    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:chromium tests

    - name: Upload Report
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: Chrome Robot Report
        path: logs

  firefox:

    runs-on: ubuntu-latest

    steps:
    - name: Get code
      uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Setup Python
      uses: actions/setup-python@v6.0.0
      with:
        python-version: 3.12

    - name: Install dependencies
      run:  |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Browser Init
      run: rfbrowser init

    - name: Run E2E Tests
      run: robot -d ./logs -v BROWSER:firefox tests

    - name: Upload Report
      uses: actions/upload-artifact@v4.6.2
      if: always()
      with:
        name: Firefox Robot Report
        path: logs